### ISSUE TITLE
API doc for brickset?

### ISSUE THREAD

**Issue by jgalan** [4Kaylum/Brickfront#3]
Hi,

I managed to make it work using python3.

Now, I have this brickset website for API reference,

https://brickset.com/tools/webservices/v2

but it seems the members are outdated.

Tutorial works perfect, but priceUK is not present in the documentation link I have, and "availability" for example is not recognized as a member.

Where can I find the full reference?

Thanks!

**Comment by 4Kaylum** [comment]
Hi! First of all, thank you for having an interest in Brickfront. Brickfront is a wrapper for the API in the link you gave. Brickfront is simply a set of classes that automatically sort out the information for you.

There are a few small changes I've made in the translation from the API into this library. For instance, `priceUK`, as you noted. In the Brickset API, it's referred to as `UKRetailPrice`. All Brickfront documentation can be [found here](https://brickfront.readthedocs.io/en/latest/index.html). 

Availability isn't a recognised attribute because I don't appear to be parsing it. I'm not entirely sure why, but that shall be something I add in the next version bump. For now, you can access the raw API call data via the `raw` attribute of any `Build` instance.
